backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use discount\models\Discount;
use product\models\Product;
use promo\models\Promo;
use sale\models\Sale;
use salepoint\models\SalePoint;
use Yii;
use yii\base\ErrorException;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use backend\models\SignupForm;
use common\models\User;

/**
 * Site controller
 */
class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'add-sale', 'get-promos', 'get-sale-points', 'get-products',],
						'allow' => true,
					],
					[
						'actions' => ['logout', 'index', 'office', 'error'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex()
	{
		return $this->render('index');
	}

	public function actionLogin()
	{
		$this->layout = 'small';

		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->loginAdmin()) {
			return $this->goBack();
		} else {
			return $this->render(
				'login',
				[
					'model' => $model,
				]
			);
		}
	}

//	public function actionSignup()
//	{
//		$this->layout = 'small';
//
//		$model = new SignupForm();
//		if ($model->load(Yii::$app->request->post())) {
//			if ($user = $model->signup()) {
//				if (Yii::$app->getUser()->login($user)) {
//					return $this->goHome();
//				}
//			}
//		}
//
//		return $this->render(
//			'signup',
//			[
//				'model' => $model,
//			]
//		);
//	}

	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	public function actionAddSale($userId, $productId)
	{
		$product = Product::findOne((int)$_GET['productId']);
		$amount = !empty($_GET['amount']) ? $_GET['amount'] : 1;
		$totalBall = 0;
		$totalPrice = 0;
		if ($product) {
			$ball = 0;
			$promo = Promo::findOne(['archive' => 0, 'user_id' => (int)$_GET['userId']]);
			$discounts = $promo ? $promo->discounts : [];
			if ($discount = Discount::findProductDiscount($discounts, $product->id)) {
				$ball = $discount->ball ? $discount->ball : 0;
				$totalPrice = ($product->price - $discount->discount * ($product->price) / 100) * $amount;
			} else {
				$totalPrice = $product->price * $amount;
			}
			$totalBall = ($totalPrice / 100) * $ball;
		}
		$model = new Sale();
		$model->user_id = (int)$_GET['userId'];
		$model->product_id = (int)$_GET['productId'];
		$model->client_name = isset($_GET['name']) ? $_GET['name'] : '';
		$model->client_last_name = isset($_GET['last_name']) ? $_GET['last_name'] : '';
		$model->salepoint_id = isset($_GET['salepointId']) ? $_GET['salepointId'] : 1;
		$model->price = $totalPrice;
		$model->status = (int)isset($_GET['status']) ? $_GET['status'] : 0;
		$model->order_id = isset($_GET['number']) ? $_GET['number'] : 0;
		$model->ball = $totalBall;
		$model->created_at = time();
		$model->amount = $amount;

		if ($model->save()) {
			$user = User::findOne($model->user_id);
			if ($user && $model->status == Sale::STATUS_PAID) {
				$user->ball += $totalBall;
				$user->save(false);
			}
			print Json::encode(['result' => 'added']);
		} else {
			print Json::encode(['result' => 'error', $model->getErrors()]);
		}
	}


	/**
	 * Функция API
	 * Выдает промо-коды пользователей
	 *
	 * Cмещение
	 *
	 * @param int $offset
	 *
	 * Лимит
	 * @param int $limit
	 */
	public function actionGetPromos($offset, $limit)
	{
		$promos = \promo\models\Promo::find()->offset($offset)->limit($limit)->all();
		$result = [];
		/* @var $promo \promo\models\Promo */
		foreach ($promos as $promo) {
			$discounts = [];
			foreach ($promo->discounts as $discount) {
				$discounts[$discount->product_id] = $discount->discount;
			};
			$result[$promo->id] = [
				'user_id' => $promo->user_id,
				'label' => $promo->label,
				'description' => $promo->description,
				'discounts' => $discounts,
				'date_from' => $promo->date_from,
				'date_to' => $promo->date_to,
			];
		}
		print Json::encode($result);
	}

	/**
	 * Функция API
	 * Выдает список продуктов
	 *
	 * Cмещение
	 *
	 * @param int $offset
	 *
	 * Лимит
	 * @param int $limit
	 */
	public function actionGetProducts($offset, $limit)
	{
		$products = \product\models\Product::find()->offset($offset)->limit($limit)->all();
		$result = [];
		/* @var $user \product\models\Product */
		foreach ($products as $product) {
			$result[$product->id] = $product->label;
		}
		print Json::encode($result);
	}

	/**
	 * Функция API
	 * Выдает точки продаж
	 *
	 * Cмещение
	 *
	 * @param int $offset
	 *
	 * Лимит
	 * @param int $limit
	 */
	public function actionGetSalePoints($offset, $limit)
	{
		$salePoints = SalePoint::find()->offset($offset)->limit($limit)->all();
		$result = [];
		/* @var $salePoint SalePoint */
		foreach ($salePoints as $salePoint) {
			$result[$salePoint->id] = $salePoint->address;
		}
		print Json::encode($result);
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use salepoint\models\SalePoint;
use common\models\User;
use Yii;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout', 'signup', 'request-password-reset', 'reset-password'],
				'rules' => [
					[
						'actions' => ['signup', 'login', 'contact', 'request-password-reset', 'reset-password', 'confirm', 'error', 'politic'],
						'allow' => true,
						'roles' => ['?'],
					],
					[
						'actions' => ['logout', 'index'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * @return \yii\web\Response
	 */
	public function actionIndex()
	{
		return $this->redirect(['/user']);
	}

	/**
	 * @return string|\yii\web\Response
	 */
	public function actionLogin()
	{
		$this->layout = 'small';
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render(
				'login',
				[
					'model' => $model,
				]
			);
		}
	}

	/**
	 * @return \yii\web\Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	/**
	 * @return string|\yii\web\Response
	 */
	public function actionContact()
	{
		$this->layout = 'small';
		$model = new ContactForm();
		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
				Yii::$app->session->setFlash(
					'success',
					'Thank you for contacting us. We will respond to you as soon as possible.'
				);
			} else {
				Yii::$app->session->setFlash('error', 'There was an error sending email.');
			}

			return $this->refresh();
		} else {
			return $this->render(
				'contact',
				[
					'model' => $model,
				]
			);
		}
	}

	/**
	 * @return string
	 */
	public function actionAbout()
	{
		return $this->render('about');
	}

	/**
	 * @return string|\yii\web\Response
	 */
	public function actionSignup()
	{
		$this->layout = 'small';
		$model = new SignupForm();
		if ($model->load(Yii::$app->request->post())) {
			if ($user = $model->signup()) {
				if ($user->sendConformation()) {
					Yii::$app->getSession()->setFlash('email', true);
				}
				return $this->goHome();
//				if (Yii::$app->getUser()->login($user)) {
//					return $this->goHome();
//				}
			}
		}
		$salepoints = SalePoint::find()->all();
		return $this->render(
			'signup',
			[
				'model' => $model,
				'salepoints' => $salepoints,
			]
		);
	}

	/**
	 * @return string|\yii\web\Response
	 */
	public function actionRequestPasswordReset()
	{
		$this->layout = 'small';
		$model = new PasswordResetRequestForm();
		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			if ($model->sendEmail()) {
				Yii::$app->getSession()->setFlash('success', 'Проверьте почту для продолжения операции.');

				return $this->goHome();
			} else {
				Yii::$app->getSession()->setFlash(
					'error',
					'Извините, мы не можем сбросить пароль для этого адреса'
				);
			}
		}

		return $this->render(
			'requestPasswordResetToken',
			[
				'model' => $model,
			]
		);
	}

	/**
	 * @param $token
	 *
	 * @return string|\yii\web\Response
	 * @throws BadRequestHttpException
	 */
	public function actionResetPassword($token)
	{
		try {
			$model = new ResetPasswordForm($token);
		} catch (InvalidParamException $e) {
			throw new BadRequestHttpException($e->getMessage());
		}

		if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
			Yii::$app->getSession()->setFlash('success', 'New password was saved.');

			return $this->goHome();
		}

		return $this->render(
			'resetPassword',
			[
				'model' => $model,
			]
		);
	}

	/**
	 * @param $id
	 * @param $key
	 *
	 * Подтверждение почты
	 *
	 * @return \yii\web\Response
	 */
	public function actionConfirm($id, $key)
	{
		$user = User::findOne(['id' => $id, 'auth_key' => $key, 'status' => User::STATUS_NOT_ACTIVE]);
		if ($user) {
			$user->status = User::STATUS_EMAIL_CONFIRMED;
			$user->save();
			Yii::$app->session->setFlash('activate');
		}

		return $this->goHome();
	}

	/**
	 * ПОЛИТИКА ОБРАБОТКИ ПЕРСОНАЛЬНЫХ ДАННЫХ
	 * @return string
	 */
	public function actionPolitic() {
		return $this->renderPartial('politic');
	}
}

frontend/views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
/* @var $this yii\web\View */
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="login-container">
	<div class="row">
		<div class="col-md-12">
			<div class="text-center m-b-md">
				<h3><?= Html::encode($this->title) ?></h3>
			</div>
			<div class="hpanel">
				<div class="panel-body">
					<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
					<?= $form->field($model, 'email') ?>
					<?= $form->field($model, 'password')->passwordInput() ?>
					<?= $form->field($model, 'rememberMe')->checkbox() ?>
					<div style="color:#999;margin:1em 0">
						Если вы забыли пароль, то вы можете <?= Html::a('сменить его', ['site/request-password-reset']) ?>.
					</div>
					<div class="form-group">
						<?= Html::submitButton('Вход', ['class' => 'btn btn-success btn-block', 'name' => 'login-button']) ?>
						<?= Html::a('Регистрация', ['/site/signup'],['class' => 'btn btn-default btn-block', 'name' => 'login-button']) ?>
					</div>
					<?php ActiveForm::end(); ?>
				</div>
			</div>
		</div>
	</div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = 'Запрос на сброс пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-container">
	<div class="row">
		<div class="col-md-12">
			<div class="text-center m-b-md">
				<h3><?= Html::encode($this->title) ?></h3>
			</div>
			<div class="hpanel">
				<div class="panel-body">
					<p>Пожалуйста введите email. Ссылка на востановление пароля будет отправлена по этому адресу.</p>

					<?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
					<?= $form->field($model, 'email') ?>
					<div class="form-group">
						<?= Html::submitButton('Отправить', ['class' => 'btn btn-primary btn-block']) ?>
					</div>
					<?php ActiveForm::end(); ?>
				</div>
			</div>
		</div>
	</div>
</div>

frontend/views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = 'Сброс пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-container">
	<div class="row">
		<div class="col-md-12">
			<div class="text-center m-b-md">
				<h3><?= Html::encode($this->title) ?></h3>
			</div>
			<div class="hpanel">
				<div class="panel-body">
					<?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
					<?= $form->field($model, 'password')->passwordInput() ?>
					<div class="form-group">
						<?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary btn-block']) ?>
					</div>
					<?php ActiveForm::end(); ?>
				</div>
			</div>
		</div>
	</div>
</div>

frontend/views/site/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-container">
	<div class="row">
		<div class="col-md-12">
			<div class="text-center m-b-md">
				<h3><?= $this->title ?></h3>
			</div>
			<div class="hpanel">
				<div class="panel-body">
					<?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
					<?= $form->field($model, 'username') ?>
					<?= $form->field($model, 'email') ?>
					<?= $form->field($model, 'password')->passwordInput() ?>
					<?= $form->field($model, 'phone') ?>
					<?= $form->field($model, 'salepoint')->widget(
						Select2::classname(),
						[
							'data' => \yii\helpers\ArrayHelper::map($salepoints, 'id', 'address'),
							'options' => [
								'placeholder' => 'Выберите место работы, адрес организации',
								'multiple' => false
							],
							'language' => 'ru',
							'pluginOptions' => [
								'allowClear' => true,
								'tags' => true,
							],
						]
					) ?>
					<?= $form->field($model, 'confirm')->checkbox() ?>
					<p class="m-b-xs">
						<?= Html::a('Агенский договор', '/files/Агенский_договор_общий.doc') ?>
					</p>
					<p>
						<?= Html::a('Политика обработки публичных данных', ['/site/politic'], ['target' => '_newWindow', 'class' => 'user-politic-signup']) ?>
					</p>
					<div class="form-group m-t">
						<?= Html::submitButton(
							'Зарегистрироваться',
							['class' => 'btn btn-default btn-block', 'name' => 'signup-button']
						) ?>
					</div>
					<?php ActiveForm::end(); ?>
				</div>
			</div>
		</div>
	</div>
</div>